### ISSUE TITLE
Remove lines between -----END CERTIFICATE----- and -----BEGIN CERTIFICATE----- when using -c and export? 

### ISSUE THREAD

**Issue by Evantage-WS** [Hakky54/certificate-ripper#10]
Hi, is there a way with -c not to have the 2 lines with text in the export between -----END CERTIFICATE----- and -----BEGIN CERTIFICATE-----, so we have a clean export ?

```
-----END CERTIFICATE-----
subject=CN=(STAGING) Doctored Durian Root CA X3,O=(STAGING) Internet Security Research Group,C=US
issuer=CN=(STAGING) Doctored Durian Root CA X3,O=(STAGING) Internet Security Research Group,C=US
-----BEGIN CERTIFICATE-----
```

**Comment by Hakky54** [comment]
Sure, I can add an option to clean out the headers/metadata. I am just curious about your use case, can you explain me how you are using and why you need it without the headers?
