### ISSUE TITLE
It doesn't actually get a fresh copy of any of the certificates

### ISSUE THREAD

**Issue by st1064870** [Hakky54/certificate-ripper#4]
I checked with Wireshark and it doesn't actually get a fresh copy of any of the certificates in the certificate chain. I guess this should be noted!

**Comment by Hakky54** [comment]
Hi, can you please explain your issue more? What do you mean by it is not getting a fresh copy of any certificate?

**Comment by st1064870** [comment]
![Screenshot from 2022-04-09 17-06-45](https://user-images.githubusercontent.com/61602820/162577741-ddc3fa44-a4fb-46e1-9423-65b11448f970.png)

**Comment by Hakky54** [comment]
Have you tried `crip export --url=https://facebook.com` It will export the chain of certificates of Facebook as individual certificate into a p12 keystore. In this case it will export 3 certificates as shown below.
The output will look like this:

<img width="1636" alt="Screenshot 2022-04-09 at 16 12 03" src="https://user-images.githubusercontent.com/16032204/162577903-1c67afaf-5f80-420f-9ae8-5a10209a9f8b.png">

**Comment by ChillVibesMushroom** [comment]
Correct me if I'm wrong but can I use this to extract a leaf certificate and use it in a man in the middle attack you seem to be the expert creator of crips and maybe you can shed some light on my dilema. I need to extract the leaf certificate of my website. Is there a tool for that.
