### ISSUE TITLE
Add support to export in the .CRT/PEM format (multiple files for chains)

### ISSUE THREAD

**Issue by OneCyrus** [Hakky54/certificate-ripper#6]
**Is your feature request related to a problem? Please describe.**
We are using your tool to automate the process of getting the current certificate behind TLS inspection. The export command is perfect to get the full certificate chain but unfortunately on in most use cases we need the certificates in the .crt format and each certificate needs to have its own file. At the moment we are doing this converting and exporting inside a dockerfile ike this:

```
RUN sudo wget https://github.com/Hakky54/certificate-ripper/releases/download/1.0.0/crip-linux-amd64.tar.gz --no-check-certificate --output-document /tmp/crip-linux-amd64.tar.gz
RUN sudo tar xzvf /tmp/crip-linux-amd64.tar.gz -C /tmp
RUN sudo /tmp/crip export --url=https://www.google.com --destination /tmp
# add "-legacy" on ubuntu 22.04 to openssl
RUN sudo openssl pkcs12 -in /tmp/truststore.p12 -out /tmp/mitm.pem -password pass:changeit 
RUN sudo chmod 777 /tmp/mitm.pem
RUN sudo csplit --prefix=mitm- --suffix-format=%d.crt /tmp/mitm.pem '/^-----END /1' '{*}'
RUN sudo mv /mitm-* /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

**Describe the solution you'd like**
It would be perfect to have an export command in crip which would output multiple .crt files which can be used for certificate stores in e.g. Ubuntu. This would remove the need to do complex string manipulations.

**Describe alternatives you've considered**
As a workaround we are using the docker steps above

**Comment by Hakky54** [comment]
Hi Daniel,

Thank you for this feature request and amazing to see how you use a workaround with Docker to get it working.
What you are trying can be built in into this application. I will keep you updated here about the progress.

**Comment by Hakky54** [comment]
@OneCyrus I have a working implementation, see here for the changes https://github.com/Hakky54/certificate-ripper/pull/7

For you use case the command will be:
```
crip export pem --url=https://www.google.com
```

There is now an additional subcommand which the end-user needs to define when it wants to export. It is also possible to export to a binary form aka der. The file extension for der will be .crt and for pem files .pem. If you want the pem or der files combined in a sigle file you can pass the `--combined=true` or `-c=true` as option.

Please let me know if this solution would do the trick for you.

See also for the screenshots below:
<img width="1212" alt="Screenshot 2022-12-24 at 02 34 39" src="https://user-images.githubusercontent.com/16032204/209416976-54477619-fb42-42f1-ad2f-6af3c7b4fbbe.png">

**Comment by OneCyrus** [comment]
woah, awesome. that was fast! Thanks! 😎

Just looked in the GitHub Actions but unfortunately no artifact is captured there. As soon as there is a binary I'll can give this a try. But looks exactly what I was hoping for.

**Comment by Hakky54** [comment]
The binaries are now available here: https://github.com/Hakky54/certificate-ripper/releases
You can grab the one you need for the latest version, in this case v2.0.0 

Enjoy mate!

**Comment by OneCyrus** [comment]
just tried it and it almost worked. unfortunately ubuntu doesn't accept the file extension .pem. The exported certs need to be with the .crt extension in the /usr/local/share/ca-certificates/ directory. renaming the exported .pem files to .crt did work.

also another small thing which I expected to be different is the export with `--combined=true` and the `--destination` flag. I expected to define a filename with destination when I set to combine it. the result was that nothing got exported and it didn't show any error. Would be great to be able to set an explicit file in the combined scenario so I have the export always in the same file independent of the domain.

but already a big step forward! thanks!

**Comment by Hakky54** [comment]
Ah, I didn't know the .pem extension would not work. I have adjusted it and next to that it is possible to provide a custom filename when using combined option instead of using the auto generated from the host. Before releasing the final version. I have attached the executable into this message, you can try it out and provide your feedback here. Can you retry on your side?
[crip-linux-amd64.tar.gz](https://github.com/Hakky54/certificate-ripper/files/10304904/crip-linux-amd64.tar.gz)

**Comment by OneCyrus** [comment]
perfect, that did the trick! thank you!

the part in the dockerfile is now much simpler
```
RUN wget https://github.com/Hakky54/certificate-ripper/files/10305087/crip-linux-amd64.tar.gz --no-check-certificate -qO- | tar xvz -C /tmp/
RUN sudo /tmp/crip export pem --url=https://www.google.com --destination /usr/local/share/ca-certificates/
RUN sudo /tmp/crip export pem --url=https://www.google.com --combined=true --destination /tmp/mitm.pem
RUN sudo update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/tmp/mitm.pem
```

**Comment by Hakky54** [comment]
Great to see it now has the additional features you wanted. Your docker file looks much cleaner, amazing to see the difference! I will do some cleanup this week and release a final version. Enjoy mate.
