### ISSUE TITLE
No Linux aarch64 binary anymore?

### ISSUE THREAD

**Issue by Antiz96** [Hakky54/certificate-ripper#9]
Hi,

*Sorry it is not really a bug report per say...*

I'm maintaining the `certificate-rippper-bin` [AUR package](https://aur.archlinux.org/packages/certificate-ripper-bin) and I noticed there's no Linux aarch64 binary in the latest 2.0.1 release. Did you forget it or is it intended?
It's just to know if I should drop aarch64 support on the AUR package side as well :)

Regards,
Antiz

**Comment by Hakky54** [comment]
I have the binary ready, but I forgot to upload it. It was a bit late :)
I am supporting it, dont worry :) And thank you for mauntaining the AUR package.

**Comment by Antiz96** [comment]
> I have the binary ready, but I forgot to upload it. It was a bit late :) I am supporting it, dont worry :) And thank you for mauntaining the AUR package.

Alright then, I'll update the AUR package once the binary will be uploaded :)
You're welcome ;)

**Comment by Hakky54** [comment]
I just uploaded it, enjoy!
